[package]
name = "render"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true

[[bin]]
name = "31render"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
mtl = { path = "mtl" }
obj = { path = "obj" }
ppm = { path = "ppm" }
rand = "0.9.2"
